### ISSUE TITLE
Script assumes MySQL

### ISSUE THREAD

**Issue by reanimus** [joshp23/YOURLS-U-SRV#4]
I use SQLite for my installation, and the setup sets the engine assuming one is using MySQL, making the setup fail.

**Comment by reanimus** [comment]
Also worth noting the error handling doesn't work. I got a fatal error that didn't render any UI, just the PHP error output, then reloading the page looked like it fixed it. However, going to the U-SRV settings, I see this:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: usrv in .../htdocs/includes/vendor/aura/sql/src/ExtendedPdo.php:771 Stack trace: #0 .../htdocs/includes/vendor/aura/sql/src/ExtendedPdo.php(771): PDO->prepare('SELECT * FROM `...', Array) #1 .../htdocs/includes/vendor/aura/sql/src/ExtendedPdo.php(976): Aura\Sql\ExtendedPdo->prepare('SELECT * FROM `...') #2 .../htdocs/includes/vendor/aura/sql/src/ExtendedPdo.php(746): Aura\Sql\ExtendedPdo->prepareWithValues('SELECT * FROM `...', Array) #3 .../htdocs/includes/vendor/aura/sql/src/ExtendedPdo.php(523): Aura\Sql\ExtendedPdo->perform('SELECT * FROM `...', Array) #4 .../htdocs/user/plugins/usrv/plugin.php(86): Aura\Sql\ExtendedPdo->fetchObjects('SELECT * FROM `...') #5 .../htdocs/includes/functions-plugins.php(595): usrv_do_page() #6 .../htdocs/admin/plugins.php(8): yourls_plugin_ in .../htdocs/includes/vendor/aura/sql/src/ExtendedPdo.php on line 771
```

**Comment by joshp23** [comment]
>Script assumes MySQL

[Correct](https://github.com/YOURLS/YOURLS/wiki/Requirements). And also tested with MariaDB.   
>I use SQLite for my installation  

I'm assuming that you are using [this](https://github.com/ozh/yourls-sqlite)? Is that true?
>the setup sets the engine assuming one is using MySQL  

You referring to this? https://github.com/joshp23/YOURLS-U-SRV/blob/f6bd9bfacbc5faae1f70c2c50848d82d81ffb952/usrv/plugin.php#L390
>making the setup fail.

You mean that the plugin fails to create the necessary table during initialization, yes?

---

>Also worth noting 

A separate issue.

**Comment by joshp23** [comment]
Note: if line 390 is the only problem, then it should be easy enough to fix with a conditional statement checking for the plugin you are using as a disqualifying factor for that line, or a qualifying factor for an alternate line. You can either let me know and I can commit when I have time or you can submit a pull request.

**Comment by joshp23** [comment]
Incidentally, it is worth noting that the SQLite driver is _only_ compatible with YOURLS [1.7.1 and 1.7.2](https://github.com/ozh/yourls-sqlite#sqlite-driver-for-yourls-171--172). Also, don't be shocked to see all of my plugins drop support for any YOURLS version below 1.7.3 at some point.
