### ISSUE TITLE
SRV.php: srv.php is not in the "pages" directory!

### ISSUE THREAD

**Issue by Bogey** [joshp23/YOURLS-U-SRV#5]
Hi Josh,

On YOURLS I installed this plugin, but I get this error:
"SRV.php: srv.php is not in the "pages" directory!"
I'm using YOURLS 1.7.9 -- will that work with U-SRV?

Thanks

**Comment by Bogey** [comment]
I can confirm it is copied to the pages directory.

**Comment by Bogey** [comment]
Ok, for this plugin to work we need to either move the file srv.php to the OLD location of the pages folder, which is: /pages
And one could use also [this plugin](https://gist.github.com/ozh/715b9ecf34517717318a3a687252d286).

**Comment by joshp23** [comment]
thanks for the heads up. fixed with the latest release.
